#!/bin/bash

if [ $1 == "stub" ]
then
    printf "@echo off\n"
    printf "cl /W0 /EHsc /I res /Zi /Gm /LD /FeUSMCDLL.dll misc/Stub.cpp /link /MACHINE:X86\n"
    printf "move USMCDLL.dll build\n"
    printf "move USMCDLL.lib build\n"
    exit
fi

if [ $1 == "native" ]
then
    printf "@echo off\n"
    printf "cl /W0 /EHsc /Zi /Gm /I . /I res /Fe$2.exe "
    find device ctrl-lib cli -name "*.cpp" -or -name "*.cxx" | awk -F/ '{print $0}' | tr '\n' ' '
    printf " /link /MACHINE:X86 build\\\\USMCDLL.lib\n"
    printf "move $2.exe build\n"
    exit
fi

if [ $1 == "native-lib" ]
then
    printf "@echo off\n"
    printf "cl /Zi /W0 /EHsc /Gm /I . /I res /LD /Fe$2.dll "
    find device ctrl-lib cli -name "*.cpp" -or -name "*.cxx" | awk -F/ '{print $0}' | tr '\n' ' '
    printf " /link /MACHINE:X86 build\\\\USMCDLL.lib\n"
    printf "lib /OUT:$2.lib *.obj\n"
    printf "move $2.dll build\n"
    printf "move $2.lib build\n"
    exit
fi

if [ $1 == "clr" ]
then
    printf "@echo off\n"
    printf "cl /clr /Zi /Gm /W0 /I . /I res /Fe$2.exe "
    find device ctrl-lib cli -name "*.cpp" -or -name "*.cxx" | awk -F/ '{print $0}' | tr '\n' ' '
    printf " /link USMCDLL.lib\n"
    exit
fi

if [ $1 == "clr-lib" ]
then
    printf "@echo off\n"
    printf "cl /clr /Zi /Gm /W0 /I . /I res /LD /Fe$2.dll "
    find device ctrl-lib cli -name "*.cpp" -or -name "*.cxx" | awk -F/ '{print $0}' | tr '\n' ' '
    printf " /link USMCDLL.lib\n"
    printf "lib /OUT:$2.lib *.obj\n"
    exit
fi

if [ $1 == "ui" ]
then
	printf "@echo off\n"
	printf "cl /EHsc /Zi /Gm /std:c++latest /W0 /I. /I res /I ui /I %%1\\include /I %%1\\lib\\\\vc_dll\\mswu /Fe$2.exe "
    find ui -name "*.cpp" -or -name "*.cxx" | awk -F/ '{print $0}' | tr '\n' ' '
	printf " /link %%1\\lib\\\\vc_dll\\wxmsw31u.lib build\\\\USMCDLL.lib build\\\\8smc1.lib /MACHINE:x86\n"
	printf "copy %%1\\\\lib\\\\vc_dll\wxmsw310u_vc_custom.dll build\n"
	printf "move $2.exe build\n"
	exit
fi

mkdir -p winbuild
./misc/gen-winbuild stub > winbuild/build-stub.bat
./misc/gen-winbuild native 8smc1 > winbuild/build-exe.bat
./misc/gen-winbuild native-lib 8smc1 > winbuild/build-dll.bat
./misc/gen-winbuild clr 8smc1 > winbuild/build-clr.bat
./misc/gen-winbuild clr-lib 8smc1 > winbuild/build-clr-dll.bat
./misc/gen-winbuild ui ui > winbuild/build-ui.bat