@echo off
REM This file is autogenerated by /misc/gen-winbuild script
cl /Zi /W0 /EHsc /Gm /I . /MD /LD /Fedev_standart.dll /I res device/standart/8SMC1Device.cpp device/standart/NL300Instrument.cpp device/standart/StandartDeviceManager.cpp  /link /MACHINE:X86 build\calx.lib build\USMCDLL.lib
lib /OUT:dev_standart.lib build\USMCDLL.lib 8SMC1Device.obj NL300Instrument.obj StandartDeviceManager.obj 
move dev_standart.dll build
move dev_standart.lib build
