@echo off
REM This file is autogenerated by /misc/gen-winbuild script
cl /Zi /W0 /EHsc /Gm /I . /MD /LD /Fedev_8smc1.dll /I res device/8smc1/8SMC1Device.cpp device/8smc1/8SMC1DeviceManager.cpp  /link /MACHINE:X86 build\calx.lib build\USMCDLL.lib
lib /OUT:dev_8smc1.lib build\USMCDLL.lib 8SMC1Device.obj 8SMC1DeviceManager.obj 
move dev_8smc1.dll build
move dev_8smc1.lib build
